### ISSUE TITLE
Admin user initialization

### ISSUE THREAD

**Issue by huberzeljko** [Rhetos/AspNetFormsAuth#3]
Plugin is automatically creating admin user account which is causing errors when using custom Principal fields that are required since plugin is only initializing `Name` field for admin user. 

1. Is there any common workaround to override admin user creation?
2. Is it possible to disable default admin creation?

**Comment by bantolov** [comment]
Hi,
There is no common way to suppress or change the *admin* user creation. In addition, there are multiple features and plugins that use or extends the Principal entity, so it is recommended to make every extension "backward compatible" in a way to minimize dependencies between different features.

I would recommend to make the new feature optional (for example the new property should not be Required in DSL script), or make it required for a specific usage (for example, set the default for admin user with `DefaultValue`, or use `InvalidData` instead of `Required` to make sure the new property is required for every principal except admin).

**Comment by huberzeljko** [comment]
How can I set `DefaultValue` under condition that it applies for principals with Name 'admin'?

**Comment by bantolov** [comment]
The following example sets the default value "SomeDefaultValueForAdmin" if the user is "admin". Otherwise it and leaves the value unchanged.

```c
ShortString SomeField
{
  DefaultValue 'item => (item.Name == "admin")
    ? "SomeDefaultValueForAdmin"
    : item.SomeField';
}
```
